pip install colorama
pip install termcolor
pip install keyboard
pip install urllib3
pip install pyinstaller
pip install datetime
pip install pysimplegui
pip install crypto
pip install pycryptodome
pip install pypiwin32
pip install win32crypt
pip install discord-webhook